### ISSUE TITLE
Make a mobile version with a different layout for phones and tablets.

### ISSUE THREAD

**Issue by wouterbeek** [Vrijheid-Zonder-Maar/vzm-backend#12]

**Comment by wouterbeek** [comment]
Slightly more generic point: very small and very big screens.

**Comment by charifmews** [comment]
Proposal for which screens to support and how: 
smallest screen: Iphone 4 (320x480) 
big screen: use a max-width in combination with centered container

**Comment by charifmews** [comment]
For the smallest screen use a hamburger menu or go for graceful degradation removing some categories. Personal preference is graceful degradation (in case there are too many categories for the screen width) and not the hamburger menu because of UX reasons (source:http://deep.design/the-hamburger-menu/)
